### ISSUE TITLE
Text Engine To-Do

### ISSUE THREAD

**Issue by EzioisAwesome56** [EzioisAwesome56/gameboy-thing#1]
- [x] add lowercase, puncuation and numbers
- [x] draw a textbox
- [x] clear textbox without turning LCD off
- [x] print characters one by one
- [x] blink cursor
- [x] remove textbox from screen
